version: "2.3"
services:
  catcher:
    image: coffeespiller/catcher:latest
    container_name: catcher
    ports:
      - 1515:1515
    environment:
      - LISTENING_PORT=1515
      - DESTINATION_ADDRESS=40.67.214.80
      - DESTINATION_PORT=9200
