# This is a basic workflow to help you get started with Actions

name: Coffee Spiller Catcher

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: actions-hub/docker/login@master
      env:
        DOCKER_USERNAME: coffeespiller
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & Push
      run: |
        echo ${IMAGE_TAG}
        if [ ${IMAGE_TAG} == "master" ]; then
          export DOCKER_TAG=latest
          docker build -t index.docker.io/coffeespiller/catcher:${DOCKER_TAG} .
        else
          export DOCKER_TAG=${IMAGE_TAG}
          docker build -t index.docker.io/coffeespiller/catcher:${DOCKER_TAG} .
        fi
        echo "Image built is: index.docker.io/coffeespiller/catcher:${DOCKER_TAG}"
        echo "Pushing the image"
        docker push index.docker.io/coffeespiller/catcher:${DOCKER_TAG}

    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2.0.2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_CHANNEL: codebase
        SLACK_USERNAME: coffee-buddy
        SLACK_COLOR: good
        SLACK_MESSAGE: 'New catcher! :rocket:'
