# This is a basic workflow to help you get started with Actions

name: Coffee Spiller Catcher

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: actions-hub/docker/login@master
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build :latest
      run: docker build -t coffeespiller/catcher:latest .

    - name: Push to docker hub :latest
      run: docker push coffeespiller/catcher:latest

    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2.0.2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_CHANNEL: codebase
        SLACK_USERNAME: coffee-buddy
        SLACK_COLOR: good
        SLACK_MESSAGE: 'New catcher! :rocket:'
